jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Display current branch
      run: git branch --show-current
      
    - name: List directory contents
      run: ls -al

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./requirements.txt

    - name: Run tests
      run: |
        # Add your test command here, for example:
        # pytest

    - name: Build and deploy (if applicable)
      run: |
        # Add your deployment commands here, if applicable
