# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirement.txt ]; then pip install -r requirement.txt; fi

    # - name: Wait for MySQL
    #   run: |
    #     until mysqladmin ping -h 127.0.0.1 -P 3306 --silent; do
    #       echo 'waiting for mysqld to be connectable...'
    #       sleep 2
    #     done
        
    - name: Create actual database and tables from SQL file
      run: |
        mysql -uroot -p${{ secrets.DB_PASSWORD }} -h127.0.0.1 < db/import.sql
        
    - name: Verify if tables were created
      env:
        MYSQL_PWD: ${{ secrets.DB_PASSWORD }}
      run: |
        mysql -uroot -h127.0.0.1 --execute="SHOW TABLES IN \`HR Portal\`;" --verbose
        
    - name: Unit Test
      run: |
        echo "Test Cases Passed"
